INSERT INTO CARD_APPLICATIONS (FIRST_NAME,LAST_NAME, OIB, STATUS, USER_CREATED, USER_MODIFIED, DATE_CREATED, DATE_MODIFIED)
VALUES ('Ivo', 'Ivić','11111111119','Rejected','SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('Ante', 'Antić','22222222226','Approved', 'SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('Ana', 'Anić', '33333333335', 'Pending','SYSTEM', 'SYSTEM', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
