CREATE TABLE CARD_APPLICATIONS
(
    ID                  BIGSERIAL PRIMARY KEY,
    FIRST_NAME          VARCHAR(150) NOT NULL,
    LAST_NAME           VARCHAR(150) NOT NULL,
    OIB                 VARCHAR(11) NOT NULL ,
    STATUS              VARCHAR(20) NOT NULL,
    USER_CREATED        VARCHAR(20)  ,
    USER_MODIFIED       VARCHAR(20)  ,
    DATE_CREATED        TIMESTAMP    NOT NULL,
    DATE_MODIFIED       TIMESTAMP    NOT NULL,
    CONSTRAINT UQ_CARD_APPLICATIONS_Number UNIQUE (OIB)
);
